
- name: Import Bacula key from bacula.org
  rpm_key:
    state: present
    key: https://www.bacula.org/downloads/Bacula-4096-Distribution-Verification-key.asc

- name: Upload repo template
  template:
    src: etc/yum.repos.d/bacula.repo
    dest: /etc/yum.repos.d/bacula.repo
    owner: root
    group: root
    mode: 644

- name: Stat config dir
  stat:
    path: "/etc/bacula"
  register: bacula_config_dir

- name: Move old config dir
  command: mv /etc/bacula /etc/bacula.old
  when: "bacula_config_dir.stat.islnk is defined and bacula_config_dir.stat.islnk == False"

- name: Create STD DIRs
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: bacula
    mode: 0770
  with_items:
    - /var/lib/bacula
    - /usr/lib/bacula
    - /var/spool/bacula
